[package]
name = "aws-token-rotate"
version = "1.0.1"
authors = ["Maxime Cottret <maxime.cottret@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0"
clap = "3.0.0-beta.2"
rusoto_core = "0.45"
rusoto_iam = "0.45"
tokio = "0.2"
configparser = "1.0"
